### ISSUE TITLE
Cannot build html5 / flash from source on ubuntu

### ISSUE THREAD

**Issue by derek-adair** [moxiecode/moxie#120]
I dont really care about silverlight, so i'm assuming i dont *need* a windows VM.  Booting up a windows VM to build this *is* possible just a bit of a pain, hopefully the rest of the build process is not dependent on windows.

I should also note that i'm using nvm, which could possibly have implications here.  I should also note that i'm not very savvy w/ node, so my lack of comprehension may be an issue.  I suspect it boils down to a config issue.

Anyways, here is the error:

    ➜  moxie git:(3e0475c) jake mkjs -t
    jake aborted.
    TypeError: Cannot call method 'debug' of undefined
        at parseModule (/mnt/django-ajax-uploader/demo/s3direct/static/ajaxuploader/plupload/src/moxie/node_modules/amdlc/lib/AmdCompiler.js:204:19)
        at /mnt/django-ajax-uploader/demo/s3direct/static/ajaxuploader/plupload/src/moxie/node_modules/amdlc/lib/AmdCompiler.js:238:3
        at Array.forEach (native)
        at Object.parseModules (/mnt/django-ajax-uploader/demo/s3direct/static/ajaxuploader/plupload/src/moxie/node_modules/amdlc/lib/AmdCompiler.js:237:49)
        at Object.resolveModules (/mnt/django-ajax-uploader/demo/s3direct/static/ajaxuploader/plupload/src/moxie/build/mkjs.js:27:19)
        at targetDir [as action] (/mnt/django-ajax-uploader/demo/s3direct/static/ajaxuploader/plupload/src/moxie/Jakefile.js:69:17)
        at TaskBase.run (/home/derek/.nvm/v0.10.33/lib/node_modules/jake/lib/task/task.js:247:27)
        at TaskBase.runPrereqs (/home/derek/.nvm/v0.10.33/lib/node_modules/jake/lib/task/task.js:159:12)
        at TaskBase.invoke (/home/derek/.nvm/v0.10.33/lib/node_modules/jake/lib/task/task.js:104:10)
        at TaskBase.nextPrereq (/home/derek/.nvm/v0.10.33/lib/node_modules/jake/lib/task/task.js:193:26)

**Comment by jayarjo** [comment]
This is some inconsistency in `amdlc` package. I've stumbled on it recently as well. Not yet sure why it is happening, but it is easy to overcome if you simply comment out those _reporter_ lines, at those specified locations (e.g. /mnt/django-ajax-uploader/demo/s3direct/static/ajaxuploader/plupload/src/moxie/node_modules/amdlc/lib/AmdCompiler.js:204:19).

**Comment by jayarjo** [comment]
Fixed the problem in my fork that is referenced for now in moxies `package.json`.
